# This rule is not used by the project openmetadata-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to openmetadataentitytags.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openmetadata-operator
    app.kubernetes.io/managed-by: kustomize
  name: openmetadataentitytag-viewer-role
rules:
- apiGroups:
  - openmetadata.vortexa.com
  resources:
  - openmetadataentitytags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openmetadata.vortexa.com
  resources:
  - openmetadataentitytags/status
  verbs:
  - get
