---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openmetadata.vortexa.com
  resources:
  - ingestionpipelines
  - openmetadataentitytags
  - openmetadataservices
  - openmetadatatestcases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openmetadata.vortexa.com
  resources:
  - ingestionpipelines/finalizers
  - openmetadataentitytags/finalizers
  - openmetadataservices/finalizers
  - openmetadatatestcases/finalizers
  verbs:
  - update
- apiGroups:
  - openmetadata.vortexa.com
  resources:
  - ingestionpipelines/status
  - openmetadataentitytags/status
  - openmetadataservices/status
  - openmetadatatestcases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openmetadata.vortexa.com
  resources:
  - openmetadataconnections
  verbs:
  - get
  - list
  - watch
