//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AirflowConfig) DeepCopyInto(out *AirflowConfig) {
	*out = *in
	if in.StartDate != nil {
		in, out := &in.StartDate, &out.StartDate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AirflowConfig.
func (in *AirflowConfig) DeepCopy() *AirflowConfig {
	if in == nil {
		return nil
	}
	out := new(AirflowConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSpec) DeepCopyInto(out *ConnectionSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSpec.
func (in *ConnectionSpec) DeepCopy() *ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityMatch) DeepCopyInto(out *EntityMatch) {
	*out = *in
	if in.Includes != nil {
		in, out := &in.Includes, &out.Includes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Excludes != nil {
		in, out := &in.Excludes, &out.Excludes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityMatch.
func (in *EntityMatch) DeepCopy() *EntityMatch {
	if in == nil {
		return nil
	}
	out := new(EntityMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityReference) DeepCopyInto(out *EntityReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityReference.
func (in *EntityReference) DeepCopy() *EntityReference {
	if in == nil {
		return nil
	}
	out := new(EntityReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionPipeline) DeepCopyInto(out *IngestionPipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionPipeline.
func (in *IngestionPipeline) DeepCopy() *IngestionPipeline {
	if in == nil {
		return nil
	}
	out := new(IngestionPipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngestionPipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionPipelineList) DeepCopyInto(out *IngestionPipelineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IngestionPipeline, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionPipelineList.
func (in *IngestionPipelineList) DeepCopy() *IngestionPipelineList {
	if in == nil {
		return nil
	}
	out := new(IngestionPipelineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IngestionPipelineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionPipelineOMSpec) DeepCopyInto(out *IngestionPipelineOMSpec) {
	*out = *in
	out.Service = in.Service
	in.SourceConfig.DeepCopyInto(&out.SourceConfig)
	in.AirflowConfig.DeepCopyInto(&out.AirflowConfig)
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]EntityReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionPipelineOMSpec.
func (in *IngestionPipelineOMSpec) DeepCopy() *IngestionPipelineOMSpec {
	if in == nil {
		return nil
	}
	out := new(IngestionPipelineOMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionPipelineSpec) DeepCopyInto(out *IngestionPipelineSpec) {
	*out = *in
	in.ForOpenMetadata.DeepCopyInto(&out.ForOpenMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionPipelineSpec.
func (in *IngestionPipelineSpec) DeepCopy() *IngestionPipelineSpec {
	if in == nil {
		return nil
	}
	out := new(IngestionPipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestionPipelineStatus) DeepCopyInto(out *IngestionPipelineStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestionPipelineStatus.
func (in *IngestionPipelineStatus) DeepCopy() *IngestionPipelineStatus {
	if in == nil {
		return nil
	}
	out := new(IngestionPipelineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataConnection) DeepCopyInto(out *OpenMetadataConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataConnection.
func (in *OpenMetadataConnection) DeepCopy() *OpenMetadataConnection {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMetadataConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataConnectionList) DeepCopyInto(out *OpenMetadataConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMetadataConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataConnectionList.
func (in *OpenMetadataConnectionList) DeepCopy() *OpenMetadataConnectionList {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMetadataConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataConnectionSpec) DeepCopyInto(out *OpenMetadataConnectionSpec) {
	*out = *in
	out.AuthSecretRef = in.AuthSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataConnectionSpec.
func (in *OpenMetadataConnectionSpec) DeepCopy() *OpenMetadataConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataEntityTag) DeepCopyInto(out *OpenMetadataEntityTag) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataEntityTag.
func (in *OpenMetadataEntityTag) DeepCopy() *OpenMetadataEntityTag {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataEntityTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMetadataEntityTag) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataEntityTagList) DeepCopyInto(out *OpenMetadataEntityTagList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMetadataEntityTag, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataEntityTagList.
func (in *OpenMetadataEntityTagList) DeepCopy() *OpenMetadataEntityTagList {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataEntityTagList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMetadataEntityTagList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataEntityTagSpec) DeepCopyInto(out *OpenMetadataEntityTagSpec) {
	*out = *in
	in.Match.DeepCopyInto(&out.Match)
	out.Tag = in.Tag
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataEntityTagSpec.
func (in *OpenMetadataEntityTagSpec) DeepCopy() *OpenMetadataEntityTagSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataEntityTagSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataEntityTagStatus) DeepCopyInto(out *OpenMetadataEntityTagStatus) {
	*out = *in
	if in.TagAssignments != nil {
		in, out := &in.TagAssignments, &out.TagAssignments
		*out = make([]TagAssignment, len(*in))
		copy(*out, *in)
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataEntityTagStatus.
func (in *OpenMetadataEntityTagStatus) DeepCopy() *OpenMetadataEntityTagStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataEntityTagStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataService) DeepCopyInto(out *OpenMetadataService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataService.
func (in *OpenMetadataService) DeepCopy() *OpenMetadataService {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMetadataService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataServiceList) DeepCopyInto(out *OpenMetadataServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMetadataService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataServiceList.
func (in *OpenMetadataServiceList) DeepCopy() *OpenMetadataServiceList {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMetadataServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataServiceSpec) DeepCopyInto(out *OpenMetadataServiceSpec) {
	*out = *in
	in.ForOpenMetadata.DeepCopyInto(&out.ForOpenMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataServiceSpec.
func (in *OpenMetadataServiceSpec) DeepCopy() *OpenMetadataServiceSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataServiceStatus) DeepCopyInto(out *OpenMetadataServiceStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataServiceStatus.
func (in *OpenMetadataServiceStatus) DeepCopy() *OpenMetadataServiceStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataTestCase) DeepCopyInto(out *OpenMetadataTestCase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataTestCase.
func (in *OpenMetadataTestCase) DeepCopy() *OpenMetadataTestCase {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataTestCase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMetadataTestCase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataTestCaseList) DeepCopyInto(out *OpenMetadataTestCaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMetadataTestCase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataTestCaseList.
func (in *OpenMetadataTestCaseList) DeepCopy() *OpenMetadataTestCaseList {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataTestCaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMetadataTestCaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataTestCaseSpec) DeepCopyInto(out *OpenMetadataTestCaseSpec) {
	*out = *in
	in.ForOpenMetadata.DeepCopyInto(&out.ForOpenMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataTestCaseSpec.
func (in *OpenMetadataTestCaseSpec) DeepCopy() *OpenMetadataTestCaseSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataTestCaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMetadataTestCaseStatus) DeepCopyInto(out *OpenMetadataTestCaseStatus) {
	*out = *in
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMetadataTestCaseStatus.
func (in *OpenMetadataTestCaseStatus) DeepCopy() *OpenMetadataTestCaseStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMetadataTestCaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceOMSpec) DeepCopyInto(out *ServiceOMSpec) {
	*out = *in
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]EntityReference, len(*in))
		copy(*out, *in)
	}
	in.Connection.DeepCopyInto(&out.Connection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceOMSpec.
func (in *ServiceOMSpec) DeepCopy() *ServiceOMSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceOMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagAssignment) DeepCopyInto(out *TagAssignment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagAssignment.
func (in *TagAssignment) DeepCopy() *TagAssignment {
	if in == nil {
		return nil
	}
	out := new(TagAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagRef) DeepCopyInto(out *TagRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagRef.
func (in *TagRef) DeepCopy() *TagRef {
	if in == nil {
		return nil
	}
	out := new(TagRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestCaseOMSpec) DeepCopyInto(out *TestCaseOMSpec) {
	*out = *in
	if in.ParameterValues != nil {
		in, out := &in.ParameterValues, &out.ParameterValues
		*out = make([]TestCaseParameterValue, len(*in))
		copy(*out, *in)
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]EntityReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestCaseOMSpec.
func (in *TestCaseOMSpec) DeepCopy() *TestCaseOMSpec {
	if in == nil {
		return nil
	}
	out := new(TestCaseOMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestCaseParameterValue) DeepCopyInto(out *TestCaseParameterValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestCaseParameterValue.
func (in *TestCaseParameterValue) DeepCopy() *TestCaseParameterValue {
	if in == nil {
		return nil
	}
	out := new(TestCaseParameterValue)
	in.DeepCopyInto(out)
	return out
}
